server:
  port: 8081
spring:
  application:
    name: Member
  datasource:
    username: root
    password: root
    url: jdbc:mysql://106.12.182.12:3306/Book?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 106.12.182.12
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 106.12.145.214
mybatis:
  mapperLocations: classpath:mybatis/*.xml

#redis config start
  # redis配置，以下有默认配置的也可以使用默认配置




TokenSalt : "a1b2c3ddd"