server:
  port: 8081
  #mybatis:
#  mapperLocations: classpath:mybatis/*.xml

TokenSalt : "a1b2c3ddd"

nacos:
  config:
    server-addr: 106.12.145.214:8848
    auto-refresh: true

spring:
  application:
    name: Resolver-Service
  cloud:
    nacos:
      discovery:
        server-addr: 106.12.145.214:8848


