server:
  port: 8082

nacos:
  config:
    server-addr: 106.12.145.214:8848
    auto-refresh: true

spring:
  application:
    name: Resolver-operation
  cloud:
    nacos:
      discovery:
        server-addr: 106.12.145.214:8848


